version: '3.8'
services:
  app:
    build: ./app
    command: node index.js
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=development
